version: '3.8'
services:
  go-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 8080:8080
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/product/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/product/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
