version: '3.8'
services:
  go-app:
    image: registry.cn-chengdu.aliyuncs.com/1in/go-product:latest
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 8080:8080
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/product/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
  ports:
      - 6379:6379
    image: redis
    volumes:
      - /Users/product/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
